<?php

/**
 * Created by PhpStorm.
 * User: nicolas
 * Date: 03/05/17
 * Time: 11:33
 */
class UserController extends Controller
{

    /**
     * @var
     */
    private $model;

    /**
     * @return mixed
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * @param mixed $model
     */
    public function setModel($model)
    {
        $this->model = $model;
    }

    /**
     * UserController constructor.
     * @param $view
     */
    public function __construct($view)
    {
        $user = new UserModel("User");
        $this->setModel($user);
        parent::__construct($view);

    }

    /**
     * @param $view
     */
    public function render($view)
    {

        parent::render($view); // TODO: Change the autogenerated stub


    }

}